### ISSUE TITLE
DBpediaSpotlight host and port no longer valid

### ISSUE THREAD

**Issue by estefaniaotero** [marcocor/bat-framework#6]
DBpediaSpotlight configuation is no longer valid in SpotlightAnnotator.java class, host "spotlight.dbpedia.org" and port 80 are not working right now. You can use host = "spotlight.sztaki.hu" and port=2222.

**Comment by marcocor** [comment]
Thanks for bringing this up. Before embedding the new URL into the next version of the BAT-Framework, do you have any information on the stability of the service at sztaki.hu? Is it going to be maintained for a decently long time?

Note that, even before a new release of the BAT-Framework, you can use the new address by constructing the annotator as:
`SpotlightAnnotator ann = new SpotlightAnnotator(DisambiguationPolicy.Default, new DBPediaApi(), wikiApi, "spotlight.sztaki.hu", 2222);`

Thanks, cheers.

**Comment by estefaniaotero** [comment]
I honestly have no idea of service stability at sztaki.hu. I was looking for another endpoint to execute experiments on DBpedia Spotlight and I find it. Gerbil is using the same endpoint for the service as well. 
And, yes, I was using personalized constructor to change address, but I wanted to inform about the unavailable service :-)

Cheers

**Comment by marcocor** [comment]
That seems to be the endpoint suggested by the official page of the [project](https://github.com/dbpedia-spotlight/dbpedia-spotlight/blob/master/README.md). I have included it in release candidate 1.3.2.rc1, which will be available through the Maven Central Repository in, say, a few hours :)
Thanks again.
