### ISSUE TITLE
Data set meij

### ISSUE THREAD

**Issue by TheNomet** [marcocor/bat-framework#7]
Good afternoon.
I'm actually looking in your data set archive, and I can't understand the structure of the wsdm2012_annotations.txt file. In particular the number in the middle.
Thanks for the help

**Comment by marcocor** [comment]
Hi,
the format is `tweet_id \t wikipedia_id \t mention`

where:
- `tweet_id` is the unique identifier of the twitter message
- `wikipedia_id` is the unique identifier of the entity (Wikipedia page about entity mentioned by the tweet)
- `mention` is the substring of the tweet referring to that entity.

For example:
`10048488691728385	2945494	Benefit concert`
means that mention "Benefit concert" in tweet 10048488691728385 points to Wikipedia page 2945494 (see [here](https://en.wikipedia.org/w/api.php?action=query&prop=info&rvprop=content&format=json&pageids=2945494))

Hope this helps.

**Comment by TheNomet** [comment]
Perfectly clear! Thanks for the fast response.
